export const GET_BLOGS_REQUEST = "GET_BLOGS_REQUEST";
export const GET_BLOGS_SUCCESS = "GET_BLOGS_SUCCESS";
export const GET_BLOGS_FAILED = "GET_BLOGS_FAILED";

export const BLOG_CREATE_REQUEST = "BLOG_CREATE_REQUEST";
export const BLOG_CREATE_SUCCESS = "BLOG_CREATE_SUCCESS";
export const BLOG_CREATE_FAILED = "BLOG_CREATE_FAILED";
export const BLOG_CREATE_RESET = "BLOG_CREATE_RESET";

export const GET_BLOG_REQUEST = "GET_BLOG_REQUEST";
export const GET_BLOG_SUCCESS = "GET_BLOG_SUCCESS";
export const GET_BLOG_FAILED = "GET_BLOG_FAILED";
export const GET_BLOG_RESET = "GET_BLOG_RESET";

export const BLOG_BOOKMARK_REQUEST = "BLOG_BOOKMARK_REQUEST";
export const BLOG_BOOKMARK_SUCCESS = "BLOG_BOOKMARK_SUCCESS";
export const BLOG_BOOKMARK_FAILED = "BLOG_BOOKMARK_FAILED";
export const BLOG_BOOKMARK_RESET = "BLOG_BOOKMARK_RESET";

export const BLOG_REMOVE_BOOKMARK_REQUEST = "BLOG_REMOVE_BOOKMARK_REQUEST";
export const BLOG_REMOVE_BOOKMARK_SUCCESS = "BLOG_REMOVE_BOOKMARK_SUCCESS";
export const BLOG_REMOVE_BOOKMARK_FAILED = "BLOG_REMOVE_BOOKMARK_FAILED";

export const BLOG_GET_BOOKMARKS_REQUEST = "BLOG_GET_BOOKMARKS_REQUEST";
export const BLOG_GET_BOOKMARKS_SUCCESS = "BLOG_GET_BOOKMARKS_SUCCESS";
export const BLOG_GET_BOOKMARKS_FAILED = "BLOG_GET_BOOKMARKS_FAILED";
export const BLOG_GET_BOOKMARKS_RESET = "BLOG_GET_BOOKMARKS_RESET";
